# ~/iN/apps/iN-worker-G-user-api-20250402/wrangler.toml

# Worker 名称 (必须与 Terraform 中的 script_name 匹配)
name = "in-worker-g-user-api-20250402"

# 主入口脚本路径 (假设标准结构)
main = "src/index.ts"

# 兼容性日期
compatibility_date = "2025-04-15" # 建议使用新日期

# 账户 ID (硬编码)
account_id = "ed3e4f0448b71302675f2b436e5e8dd3"

# --- 运行时绑定 ---

# 绑定 D1 数据库 (用于用户数据 CRUD)
[[d1_databases]]
binding = "DB" # 代码中使用的绑定名称 (env.DB)
database_id = "159edc29-f854-4b2f-af1e-6a77a944d135" # D1 数据库的 ID

# --- Secrets ---
# (例如，如果需要连接外部认证服务，可能需要 Secret)
# 通过 env.SECRET_NAME 访问，确保已上传

# --- Vars ---
# [vars]
# 如果需要非敏感环境变量，在此定义