# ~/iN/apps/iN-worker-D-download-20250402/wrangler.toml

# Worker 名称 (必须与 Terraform 中的 script_name 匹配)
name = "in-worker-d-download-20250402"

# 主入口脚本路径 (假设标准结构)
main = "src/index.ts"

# 兼容性日期
compatibility_date = "2025-04-15" # 建议使用新日期

# 账户 ID (硬编码)
account_id = "ed3e4f0448b71302675f2b436e5e8dd3"

# --- 运行时绑定 ---

# 绑定 Durable Object (用于更新状态)
[[durable_objects.bindings]]
name = "TASK_COORDINATOR"           # 代码中使用的绑定名称 (env.TASK_COORDINATOR)
namespace_id = "136a4671d0374175ac210bc5a2603434" # TaskCoordinatorDO 的 Namespace ID

# 绑定 R2 存储桶 (用于写入图片)
[[r2_buckets]]
binding = "BUCKET" # 代码中使用的绑定名称 (env.BUCKET)
bucket_name = "in-r2-a-bucket-20250402" # R2 存储桶名称

# 绑定 Queue (用于推送元数据处理任务)
[[queues.bindings]]
binding = "METADATA_PROCESSING_QUEUE" # 代码中使用的绑定名称 (env.METADATA_PROCESSING_QUEUE)
queue_name = "in-queue-c-metadata-processing-20250402" # 对应的 Queue 名称

# --- Secrets ---
# 不需要在此显式绑定通过 wrangler secret put 上传的 Secrets。
# 代码直接通过 env.RUNTIME_UNSPLASH_ACCESS_KEY 等访问。
# 需要确保对应的 Secret 确实已上传到 Cloudflare Secrets Store。

# --- Secrets Bindings ---

# 用于访问 Unsplash API
[[unsafe.bindings]]
type = "secret_text"
name = "UNSPLASH_ACCESS_KEY"      # 代码中用 env.UNSPLASH_ACCESS_KEY 访问
text = "RUNTIME_UNSPLASH_ACCESS_KEY" # Secrets Store 中的密钥名称

# 用于通过 S3 API 访问 R2
[[unsafe.bindings]]
type = "secret_text"
name = "R2_S3_ACCESS_KEY_ID"      # 代码中用 env.R2_S3_ACCESS_KEY_ID 访问
text = "RUNTIME_R2_S3_ACCESS_KEY_ID" # Secrets Store 中的密钥名称

[[unsafe.bindings]]
type = "secret_text"
name = "R2_S3_SECRET_ACCESS_KEY"  # 代码中用 env.R2_S3_SECRET_ACCESS_KEY 访问
text = "RUNTIME_R2_S3_SECRET_ACCESS_KEY" # Secrets Store 中的密钥名称

# --- Vars ---
# [vars]
# 如果需要非敏感环境变量，在此定义