# ~/iN/apps/iN-worker-A-api-gateway-20250402/wrangler.toml

name = "in-worker-a-api-gateway-20250402"
main = "src/index.ts"
compatibility_date = "2025-04-15"
account_id = "ed3e4f0448b71302675f2b436e5e8dd3"

# --- 运行时绑定 ---

# 绑定下游 API 服务
[[service_bindings]]
binding = "CONFIG_API_SERVICE" # 代码中使用的绑定名称 (env.CONFIG_API_SERVICE)
service = "in-worker-b-config-api-20250402" # 目标 Worker 名称

[[service_bindings]]
binding = "USER_API_SERVICE"
service = "in-worker-g-user-api-20250402"

[[service_bindings]]
binding = "IMAGE_QUERY_API_SERVICE"
service = "in-worker-h-image-query-api-20250402"

[[service_bindings]]
binding = "IMAGE_MUTATION_API_SERVICE"
service = "in-worker-i-image-mutation-api-20250402"

[[service_bindings]]
binding = "IMAGE_SEARCH_API_SERVICE"
service = "in-worker-j-image-search-api-20250402"

# --- Secrets ---
# 不需要显式绑定。代码通过 env.RUNTIME_HMAC_SECRET 访问。
# 确保 RUNTIME_HMAC_SECRET 已通过 wrangler secret put 上传。

# 用于验证内部 HMAC 签名
[[unsafe.bindings]]
type = "secret_text"
name = "INTERNAL_API_HMAC_SECRET" # 建议在代码中用这个名字访问
text = "RUNTIME_HMAC_SECRET"      # Secrets Store 中的密钥名称

# 用于验证 JWT 签名
[[unsafe.bindings]]
type = "secret_text"
name = "JWT_SECRET"               # 建议在代码中用这个名字访问
text = "RUNTIME_JWT_SECRET"       # Secrets Store 中的密钥名称

# --- Vars ---
# [vars]
# 可定义如日志级别等非敏感配置