# ~/iN/apps/iN-do-A-task-coordinator-20250402/wrangler.toml
# --- 用于定义 TaskCoordinatorDO 的最终配置 ---

# 部署到 Cloudflare 上的脚本名称 (使用原始、规范名称)
name = "in-do-a-task-coordinator-20250402"

# 主入口文件路径 (包含 DO 类定义)
main = "src/index.ts"

# 兼容性日期 - 请确保与您项目中其他 Worker 一致
compatibility_date = "2025-04-13"

# Cloudflare 账户 ID (直接硬编码，避免替换问题)
account_id = "ed3e4f0448b71302675f2b436e5e8dd3"

# [重要] 声明此脚本定义的 Durable Object 类
# 这会告诉 Wrangler 这个脚本包含 DO 实现
[[durable_objects.bindings]]
# name: Worker 内部用于绑定自身的名称 (通常此脚本不直接用，但必须声明)
name = "TASK_COORDINATOR_DO"
# class_name: 必须与 src/index.ts 中导出的 DO 类名完全一致
class_name = "TaskCoordinatorDO"

# [重要] 配置 Durable Object 迁移
# 这是 wrangler deploy 时创建/关联 DO Namespace 的关键
[[migrations]]
tag = "v1" # 初始版本标签，未来 DO 类结构变化时需要递增 tag
new_classes = ["TaskCoordinatorDO"] # 列出此脚本定义的 DO 类

# [说明] 无需显式定义 [build] 命令。
# 当 `main` 指向 .ts 文件且无 package.json build 脚本时，
# Wrangler 会自动使用 esbuild 进行编译和打包。

# [可选 - 其他绑定]
# (通常定义 DO 的 Worker 本身不需要，除非顶层 fetch 需要)
# [[d1_databases]]
# binding = "DB"
# database_name = "in-d1-a-database-20250402"
# ... (其他绑定如 R2, Queues, Vars, Secrets 如果需要)