# ~/iN/apps/iN-worker-F-ai-20250402/wrangler.toml

# Worker 名称 (必须与 Terraform 中的 script_name 匹配)
name = "in-worker-f-ai-20250402"

# 主入口脚本路径 (假设标准结构)
main = "src/index.ts"

# 兼容性日期
compatibility_date = "2025-04-15" # 建议使用新日期

# 账户 ID (硬编码)
account_id = "ed3e4f0448b71302675f2b436e5e8dd3"

# --- 运行时绑定 ---

# 绑定 Durable Object (用于更新最终状态)
[[durable_objects.bindings]]
name = "TASK_COORDINATOR"           # 代码中使用的绑定名称 (env.TASK_COORDINATOR)
namespace_id = "136a4671d0374175ac210bc5a2603434" # TaskCoordinatorDO 的 Namespace ID

# 绑定 D1 数据库 (用于写入 AI 结果)
[[d1_databases]]
binding = "DB" # 代码中使用的绑定名称 (env.DB)
database_id = "159edc29-f854-4b2f-af1e-6a77a944d135" # D1 数据库的 ID

# 绑定 Vectorize Index (用于写入向量)
# 注意：由于 Terraform 创建失败，此索引需要手动或通过 wrangler 创建
[[vectorize]]
binding = "VECTORIZE_INDEX" # 代码中使用的绑定名称 (env.VECTORIZE_INDEX)
index_name = "in-vectorize-a-index-20250402" # Vectorize Index 的名称

# 绑定 Cloudflare AI (如果使用内置 AI 功能)
# 这会让 env.AI 在代码中可用
[ai]
binding = "AI"

# --- Secrets ---
# 如果是调用【外部】AI 服务，则不需要上面的 [ai] 绑定，
# 而是需要通过 env.RUNTIME_EXTERNAL_AI_API_KEY 访问 Secret。
# 请确保对应的 Secret 已上传到 Cloudflare Secrets Store。

# --- Vars ---
# [vars]
# 如果需要非敏感环境变量，在此定义