# /home/ubuntu/iN/apps/in/wrangler.toml
# --- 配置 Worker "in"，用于提供前端静态应用和代理 API 请求 ---

name = "in"
# 【重要修改】main 指向新的服务器端 Worker 脚本
main = "worker.ts"
compatibility_date = "2025-04-15"
account_id = "ed3e4f0448b71302675f2b436e5e8dd3"

# 配置静态站点托管 - Wrangler 会将 ./dist 内容上传
# 当 worker.ts 调用 env.ASSET_SERVER.fetch 时，会从此目录提供文件
[site]
bucket = "./dist"

# --- 运行时绑定 ---

# 【重要修改】修正服务绑定格式，使用 [[services]]
[[services]]
# 在下面的 worker.ts 中使用的绑定名称 (env.API)
binding = "API"
# 您要绑定的实际后端 API Gateway Worker 的名称
service = "in-worker-a-api-gateway-20250402"

# --- Secrets / Vars ---
# 如果此 Worker 需要其他变量或 Secrets，在此添加
# [vars]
# MY_VAR = "example"